/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminDoaIndexRouteImport } from './routes/admin.doa.index'
import { Route as AdminDoaBaruRouteImport } from './routes/admin.doa.baru'
import { Route as AdminPenggunaIndexRouteImport } from './routes/admin.pengguna.index'
import { Route as AdminPenggunaIdRouteImport } from './routes/admin.pengguna.$id'
import { Route as AdminPenggunaBaruRouteImport } from './routes/admin.pengguna.baru'
import { Route as AdminTemplateIndexRouteImport } from './routes/admin.template.index'
import { Route as AdminTemplateUploadRouteImport } from './routes/admin.template.upload'
import { Route as AdminUndanganIndexRouteImport } from './routes/admin.undangan.index'
import { Route as AdminUndanganIdRouteImport } from './routes/admin.undangan.$id'
import { Route as AdminUndanganBaruRouteImport } from './routes/admin.undangan.baru'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoaIndexRoute = AdminDoaIndexRouteImport.update({
  id: '/doa/',
  path: '/doa/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDoaBaruRoute = AdminDoaBaruRouteImport.update({
  id: '/doa/baru',
  path: '/doa/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaIndexRoute = AdminPenggunaIndexRouteImport.update({
  id: '/pengguna/',
  path: '/pengguna/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaIdRoute = AdminPenggunaIdRouteImport.update({
  id: '/pengguna/$id',
  path: '/pengguna/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPenggunaBaruRoute = AdminPenggunaBaruRouteImport.update({
  id: '/pengguna/baru',
  path: '/pengguna/baru',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplateIndexRoute = AdminTemplateIndexRouteImport.update({
  id: '/template/',
  path: '/template/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTemplateUploadRoute = AdminTemplateUploadRouteImport.update({
  id: '/template/upload',
  path: '/template/upload',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUndanganIndexRoute = AdminUndanganIndexRouteImport.update({
  id: '/undangan/',
  path: '/undangan/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUndanganIdRoute = AdminUndanganIdRouteImport.update({
  id: '/undangan/$id',
  path: '/undangan/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUndanganBaruRoute = AdminUndanganBaruRouteImport.update({
  id: '/undangan/baru',
  path: '/undangan/baru',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/doa/baru': typeof AdminDoaBaruRoute
  '/admin/pengguna/$id': typeof AdminPenggunaIdRoute
  '/admin/pengguna/baru': typeof AdminPenggunaBaruRoute
  '/admin/template/upload': typeof AdminTemplateUploadRoute
  '/admin/undangan/$id': typeof AdminUndanganIdRoute
  '/admin/undangan/baru': typeof AdminUndanganBaruRoute
  '/admin/doa/': typeof AdminDoaIndexRoute
  '/admin/pengguna/': typeof AdminPenggunaIndexRoute
  '/admin/template/': typeof AdminTemplateIndexRoute
  '/admin/undangan/': typeof AdminUndanganIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/doa/baru': typeof AdminDoaBaruRoute
  '/admin/pengguna/$id': typeof AdminPenggunaIdRoute
  '/admin/pengguna/baru': typeof AdminPenggunaBaruRoute
  '/admin/template/upload': typeof AdminTemplateUploadRoute
  '/admin/undangan/$id': typeof AdminUndanganIdRoute
  '/admin/undangan/baru': typeof AdminUndanganBaruRoute
  '/admin/doa': typeof AdminDoaIndexRoute
  '/admin/pengguna': typeof AdminPenggunaIndexRoute
  '/admin/template': typeof AdminTemplateIndexRoute
  '/admin/undangan': typeof AdminUndanganIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/doa/baru': typeof AdminDoaBaruRoute
  '/admin/pengguna/$id': typeof AdminPenggunaIdRoute
  '/admin/pengguna/baru': typeof AdminPenggunaBaruRoute
  '/admin/template/upload': typeof AdminTemplateUploadRoute
  '/admin/undangan/$id': typeof AdminUndanganIdRoute
  '/admin/undangan/baru': typeof AdminUndanganBaruRoute
  '/admin/doa/': typeof AdminDoaIndexRoute
  '/admin/pengguna/': typeof AdminPenggunaIndexRoute
  '/admin/template/': typeof AdminTemplateIndexRoute
  '/admin/undangan/': typeof AdminUndanganIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/doa/baru'
    | '/admin/pengguna/$id'
    | '/admin/pengguna/baru'
    | '/admin/template/upload'
    | '/admin/undangan/$id'
    | '/admin/undangan/baru'
    | '/admin/doa/'
    | '/admin/pengguna/'
    | '/admin/template/'
    | '/admin/undangan/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/admin/doa/baru'
    | '/admin/pengguna/$id'
    | '/admin/pengguna/baru'
    | '/admin/template/upload'
    | '/admin/undangan/$id'
    | '/admin/undangan/baru'
    | '/admin/doa'
    | '/admin/pengguna'
    | '/admin/template'
    | '/admin/undangan'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/'
    | '/admin/doa/baru'
    | '/admin/pengguna/$id'
    | '/admin/pengguna/baru'
    | '/admin/template/upload'
    | '/admin/undangan/$id'
    | '/admin/undangan/baru'
    | '/admin/doa/'
    | '/admin/pengguna/'
    | '/admin/template/'
    | '/admin/undangan/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doa/': {
      id: '/admin/doa/'
      path: '/doa'
      fullPath: '/admin/doa/'
      preLoaderRoute: typeof AdminDoaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/doa/baru': {
      id: '/admin/doa/baru'
      path: '/doa/baru'
      fullPath: '/admin/doa/baru'
      preLoaderRoute: typeof AdminDoaBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna/': {
      id: '/admin/pengguna/'
      path: '/pengguna'
      fullPath: '/admin/pengguna/'
      preLoaderRoute: typeof AdminPenggunaIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna/$id': {
      id: '/admin/pengguna/$id'
      path: '/pengguna/$id'
      fullPath: '/admin/pengguna/$id'
      preLoaderRoute: typeof AdminPenggunaIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pengguna/baru': {
      id: '/admin/pengguna/baru'
      path: '/pengguna/baru'
      fullPath: '/admin/pengguna/baru'
      preLoaderRoute: typeof AdminPenggunaBaruRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template/': {
      id: '/admin/template/'
      path: '/template'
      fullPath: '/admin/template/'
      preLoaderRoute: typeof AdminTemplateIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template/upload': {
      id: '/admin/template/upload'
      path: '/template/upload'
      fullPath: '/admin/template/upload'
      preLoaderRoute: typeof AdminTemplateUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/undangan/': {
      id: '/admin/undangan/'
      path: '/undangan'
      fullPath: '/admin/undangan/'
      preLoaderRoute: typeof AdminUndanganIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/undangan/$id': {
      id: '/admin/undangan/$id'
      path: '/undangan/$id'
      fullPath: '/admin/undangan/$id'
      preLoaderRoute: typeof AdminUndanganIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/undangan/baru': {
      id: '/admin/undangan/baru'
      path: '/undangan/baru'
      fullPath: '/admin/undangan/baru'
      preLoaderRoute: typeof AdminUndanganBaruRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminDoaBaruRoute: typeof AdminDoaBaruRoute
  AdminPenggunaIdRoute: typeof AdminPenggunaIdRoute
  AdminPenggunaBaruRoute: typeof AdminPenggunaBaruRoute
  AdminTemplateUploadRoute: typeof AdminTemplateUploadRoute
  AdminUndanganIdRoute: typeof AdminUndanganIdRoute
  AdminUndanganBaruRoute: typeof AdminUndanganBaruRoute
  AdminDoaIndexRoute: typeof AdminDoaIndexRoute
  AdminPenggunaIndexRoute: typeof AdminPenggunaIndexRoute
  AdminTemplateIndexRoute: typeof AdminTemplateIndexRoute
  AdminUndanganIndexRoute: typeof AdminUndanganIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminDoaBaruRoute: AdminDoaBaruRoute,
  AdminPenggunaIdRoute: AdminPenggunaIdRoute,
  AdminPenggunaBaruRoute: AdminPenggunaBaruRoute,
  AdminTemplateUploadRoute: AdminTemplateUploadRoute,
  AdminUndanganIdRoute: AdminUndanganIdRoute,
  AdminUndanganBaruRoute: AdminUndanganBaruRoute,
  AdminDoaIndexRoute: AdminDoaIndexRoute,
  AdminPenggunaIndexRoute: AdminPenggunaIndexRoute,
  AdminTemplateIndexRoute: AdminTemplateIndexRoute,
  AdminUndanganIndexRoute: AdminUndanganIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
